#!/bin/bash
clear
#-------------------------------------------------------------------------------------------
# SCRIP SHADOW PROJECT PRO
# TELEGRAM: @THEFATHER12
#-------------------------------------------------------------------------------------------

# - Cores
RED='\033[1;31m'
YELLOW='\033[1;33m'
SCOLOR='\033[0m'

# - Verificar Ejecusion Como Root
[[ "$EUID" -ne 0 ]] && {
    echo -e "{RED}[x] ES NECESARIO EJECUTAR COMO USUARIO ROOT !{SCOLOR}"
    exit 1
}

# - Verificar Arquitectura Compatible
case "$(uname -m)" in
    'amd64' | 'x86_64')
        arch='64'
        ;;
    'aarch64' | 'armv8')
        arch='arm64'
        ;;
    *)
        echo -e "${RED}[x] ARQUITECTURA INCOMPATIBLE !${SCOLOR}"
        exit 1
        ;;
esac

# - Verificar OS Compatible
if grep -qs "ubuntu" /etc/os-release; then
	os_version=$(grep 'VERSION_ID' /etc/os-release | cut -d '"' -f 2 | tr -d '.')
    [[ "$os_version" -lt 1804 ]] && {
        echo -e "${RED}[x] VERSION DE UBUNTU INCOMPATIBLE !\n${YELLOW}[!] REQUIERE UBUNTU 18.04 O SUPERIOR !${SCOLOR}"
        exit 1
    }
elif [[ -e /etc/debian_version ]]; then
	os_version=$(grep -oE '[0-9]+' /etc/debian_version | head -1)
    [[ "$os_version" -lt 9 ]] && {
        echo -e "${RED}[x] VERSION DE DEBIAN INCOMPATIBLE !\n${YELLOW}[!] REQUIERE DEBIAN 9 O SUPERIOR !${SCOLOR}"
        exit 1
    }
else
    echo -e "${RED}[x] OS INCOMPATIBLE !\n${YELLOW}[!] REQUIERE SISTEMA BASE DEBIAN/UBUNTU !${SCOLOR}"
    exit 1
fi

# - Actualizar Lista/Paquetes/Sistema
dpkg --configure -a
apt update -y && apt upgrade -y
apt install unzip python3 -y

# - Deshabilita ipv6
sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -p
echo 'net.ipv6.conf.all.disable_ipv6 = 1' > /etc/sysctl.d/70-disable-ipv6.conf
sysctl -p -f /etc/sysctl.d/70-disable-ipv6.conf

# - Ejeculta instalador
[[ -e Plus ]] && rm Plus
wget raw.githubusercontent.com/thefather12/SSHPLUS/main/script/${arch}/Plus && chmod 777 Plus && ./Plus
